# Generated by Django 4.1.2 on 2022-10-08 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('registration_date', models.DateTimeField(default=datetime.date.today, verbose_name='Registration date')),
                ('end_date', models.DateTimeField(default=datetime.date.today, verbose_name='Deadline (closing) date')),
            ],
        ),
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='StagesOfStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('nick_name', models.CharField(max_length=255, verbose_name='Nick name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('Country', models.CharField(max_length=255, verbose_name='Country')),
                ('State', models.CharField(max_length=255, verbose_name='State')),
                ('City', models.CharField(max_length=255, verbose_name='City')),
                ('portfolio', models.TextField(blank=True, verbose_name='portfolio')),
                ('presentation', models.TextField(blank=True, verbose_name='Presentation')),
                ('education', models.TextField(blank=True, verbose_name='Education')),
                ('registration_date', models.DateTimeField(default=datetime.date.today, verbose_name='Registration date')),
                ('ratings', models.IntegerField(verbose_name='Ratings')),
                ('web_site', models.SlugField(max_length=255, unique=True, verbose_name='Web site')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('documents_copy', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Documents')),
                ('is_disabled', models.BooleanField(default=True, verbose_name='Disabled')),
                ('is_deleted', models.BooleanField(default=True, verbose_name='Deleted')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.availability', verbose_name='Availability')),
                ('main_purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.purposes', verbose_name='Main purpose')),
                ('main_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.skills', verbose_name='Basic skills')),
                ('stages_of_startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.stagesofstartup', verbose_name='Stages of startup')),
                ('user_rights', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.userrights', verbose_name='User rights')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsInProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.projects', verbose_name='Project')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.skills', verbose_name='Skills')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_projects_list.users', verbose_name='Author'),
        ),
    ]
